### PR TITLE
fabfile: remove python-flask, add python-requests

### PR DESCRIPTION
**Pull request by dachary**
Signed-off-by: Loic Dachary <ldachary@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
To what ceph.git change does this change correspond?

**Comment by ktdreyer** [comment]
In ceph.git, the master branch's ceph.spec.in still has `BuildRequires:  python-flask`  - does that need to change?

**Comment by dachary** [comment]
@ktdreyer yes, https://github.com/ceph/ceph/pull/3709 is waiting on the bot to confirm. I should have mentionned that but I was not expecting you to react instantly ;-) It should be in master in the next hour.

**Comment by ktdreyer** [comment]
Awesome, thanks :) I try to keep an eye on build dep changes, particularly since it (unfortunately) can impact the Jenkins build process.

**Comment by dachary** [comment]
@ktdreyer if I'm not mistaken alfredo now uses install-deps.sh and jenkins is now immune to this troubles

**Comment by ktdreyer** [comment]
That's great to hear!

**Comment by dachary** [comment]
@ktdreyer https://github.com/ceph/ceph/pull/3709 ready for review if you can

**Comment by ktdreyer** [comment]
ceph/ceph#3709 is now merged to hammer (my merge commit message fumbling notwithstanding :)

Do we need to wait until that change is on all Ceph branches before proceeding with this change to the gitbuilders?

**Comment by dachary** [comment]
I don't think we need to wait for anything since the fabfile is not automatically running.

**Comment by ktdreyer** [comment]
Sure, but anyone could run it at any time, right?

**Comment by dachary** [comment]
@ktdreyer maybe: I'm not sure how it should be done though. Do you know how ?

**Comment by ktdreyer** [comment]
(Until we can provide more automation by way of `install-deps.sh`, or pbuilder/mock...) I thought that we needed to have all the build dependencies of all Ceph branches on all the gitbuilders. For example, a gitbuilder might need to build the "dumpling" branch, where ceph/ceph#3709 has not yet been merged.

Do I have that right?

**Comment by dachary** [comment]
@ktdreyer I think you are right.

**Comment by dachary** [comment]
@ktdreyer the python-flask dependency is not needed to build any of the branches. It was introduced by error.

**Comment by ktdreyer** [comment]
Thanks for looking into that. I'll go ahead and merge this, in that case

**Pull request merged**
