### PR TITLE
fix rsync-target for rpm systems

### PR DESCRIPTION
**Pull request by liewegas**

### CODE REVIEW

**Comment by ktdreyer** [comment]
Tested on CentOS: this switches from `centos7_1_1503` to `centos7`

Tested on RHEL: this switches from `redhatenterpriseserver7_1` to `redhatenterpriseserver7`

Looks good to me.

And that's one hairy command :D

**Comment by ktdreyer** [comment]
This should ideally fix issues like 

```
2015-06-02T09:56:29.511 INFO:teuthology.orchestra.run.plana60.stderr:http://gitbuilder.ceph.com/ceph-rpm-centos7_1_1503-x86_64-basic/sha1/5a022fa4cf343ab54722ac9d46eff235c8760a53/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
```

right?

**Comment by liewegas** [comment]
precisely

**Comment by liewegas** [comment]
fwiw i've already run this to fix the affected centos gitbuilders

**Pull request merged**
